language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  
before_script:
  - sudo add-apt-repository ppa:apokluda/boost1.53 -y
  - sudo apt-get update -qq
  - sudo apt-get install libboost1.53-dev
  
script:
  - cmake .
  - make
